    services:
      db:
        container_name: postgres
        image: postgres:15.3
        environment:
          POSTGRES_USER: shizzy
          POSTGRES_PASSWORD: password
          PGDATA: /data/postgres
        volumes:
          - db:/data/postgres
        ports:
          - "5332:5432"
        networks:
          - db
        restart: unless-stopped
      shizzy-api:
        container_name: shizzy-api
        image: shizzy0/shizzy-api
        environment:
          SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
        ports:
          - "8088:8080"
        networks:
          - db
        depends_on:
          - db
        restart: unless-stopped
      shizzy-react:
        container_name: shizzy-react
        image: shizzy0/shizzy-react
        build:
          context: frontend/react
          args:
            api_base_url: http://localhost:8088
        ports:
          - "3000:5173"
        depends_on:
          - shizzy-api
        restart: unless-stopped

    networks:
      db:
        driver: bridge

    volumes:
      db:
